### ISSUE TITLE
Error compiling contract inside ethereum directory

### ISSUE THREAD

**Issue by dhruvinparikh** [loomnetwork/loom-examples#31]
- `cd ./etheruem`
- `truffle migrate`

is throwing following error

```
Compiling your contracts...
===========================
> Compiling ./contracts/IERC20GatewayMintable.sol
> Compiling ./contracts/Migrations.sol
> Compiling ./contracts/MyMainNetCoin.sol
> Compiling ./contracts/MyMainNetToken.sol
> Compiling ./contracts/SampleERC20MintableToken.sol
> Compiling openzeppelin-solidity/contracts/GSN/Context.sol
> Compiling openzeppelin-solidity/contracts/access/Roles.sol
> Compiling openzeppelin-solidity/contracts/access/roles/MinterRole.sol
> Compiling openzeppelin-solidity/contracts/drafts/Counters.sol
> Compiling openzeppelin-solidity/contracts/introspection/ERC165.sol
> Compiling openzeppelin-solidity/contracts/introspection/IERC165.sol
> Compiling openzeppelin-solidity/contracts/math/SafeMath.sol
> Compiling openzeppelin-solidity/contracts/token/ERC20/ERC20.sol
> Compiling openzeppelin-solidity/contracts/token/ERC20/ERC20Mintable.sol
> Compiling openzeppelin-solidity/contracts/token/ERC20/IERC20.sol
> Compiling openzeppelin-solidity/contracts/token/ERC721/ERC721.sol
> Compiling openzeppelin-solidity/contracts/token/ERC721/ERC721Enumerable.sol
> Compiling openzeppelin-solidity/contracts/token/ERC721/ERC721Full.sol
> Compiling openzeppelin-solidity/contracts/token/ERC721/ERC721Metadata.sol
> Compiling openzeppelin-solidity/contracts/token/ERC721/IERC721.sol
> Compiling openzeppelin-solidity/contracts/token/ERC721/IERC721Enumerable.sol
> Compiling openzeppelin-solidity/contracts/token/ERC721/IERC721Metadata.sol
> Compiling openzeppelin-solidity/contracts/token/ERC721/IERC721Receiver.sol
> Compiling openzeppelin-solidity/contracts/utils/Address.sol
TypeError: Cannot read property '0' of null
    at detectErrors (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/run.js:289:61)
    at run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/run.js:36:29)
```

**Comment by andreipope** [comment]
Closing this as solved (TG: "Hey, I used the package-lock.json from original repository so issue got solved.")
